version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      - dependency-name: ember-data
        versions:
          - ">= 4"
      # https://github.com/ember-cli/ember-cli/issues/9307
      - dependency-name: eslint
        versions:
          - ">= 8"
      # https://github.com/villander/ember-engines-router-service/issues/67
      - dependency-name: ember-engines-router-service
        versions:
          - ">= 0.4.0 <= 4.4.1"
      # https://github.com/ember-engines/ember-engines/issues/833
      - dependency-name: ember-engines
        versions:
          - "0.9.0"
